package engine.planets;

import engine.planets.hazards.NaturalHazard;

import java.util.ArrayList;

/**
 * Created by bob on 4/11/2016.
 *
 */
public class GridRandomConstructionContext
{
	ArrayList<NaturalHazard> hazards;// TODO: 4/11/2016 fix inconsintencies across the construction context classes this should be generated by this class not a prerequisite for construction
	ArrayList<NaturalResource> naturalResources;
	ArrayList<TerrainType> surroundingTerrains;// TODO: 4/11/2016 shoul  have an intial method which determines all terrain types before actually constructing grids would als fix above issue with hazards and resources by predefining which resources hazards and terrains to have
}
